KNI_D6_web/ViewModels/Achievements/AchievementsProgressViewModel.cs
namespace KNI_D6_web.ViewModels.Achievements
{
    public class AchievementsProgressViewModel
    {
        public string Login { get; set; }
    }
}

KNI_D6_web/ViewModels/Achievements/AchievementsViewModel.cs
using KNI_D6_web.Model.Achievements;
using System.Collections.Generic;
using System.Linq;

namespace KNI_D6_web.ViewModels.Achievements
{
    public class AchievementsViewModel
    {
        public IEnumerable<IOrderedEnumerable<Achievement>> AchievementsInGroups { get; set; }
    }
}

KNI_D6_web/ViewModels/Achievements/CreateAchievementViewModel.cs
using KNI_D6_web.Model.Achievements;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace KNI_D6_web.ViewModels.Achievements
{
    public class CreateAchievementViewModel
    {
        public string AchievementName { get; set; }

        public string AhievementDescription { get; set; }

        public int AchievementValue { get; set; }

        public int? ParameterId { get; set; }

        public int GroupId { get; set; }

        public int NumberInGroup { get; set; }

        public int? SemesterId { get; set; }

        public AchievementType AchievementType { get; set; }
    }
}

KNI_D6_web/ViewModels/Achievements/CreateValueAchievementViewModel.cs
using KNI_D6_web.Model.Achievements;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace KNI_D6_web.ViewModels.Achievements
{
    public class CreateValueAchievementViewModel
    {
        public string AchievementName { get; set; }

        public string AhievementDescription { get; set; }

        public int AchievementValue { get; set; }

        public int ParameterId { get; set; }

        public int GroupId { get; set; }

        public int NumberInGroup { get; set; }

        public int? SemesterId { get; set; }

        public AchievementType AchievementType { get; set; }
    }
}

KNI_D6_web/ViewModels/Achievements/EditAchievementViewModel.cs
using KNI_D6_web.Model;
using KNI_D6_web.Model.Achievements;

namespace KNI_D6_web.ViewModels.Achievements
{
    public class EditAchievementViewModel
    {
        public int Id { get; set; }

        public int AchievementsGroupId { get; set; }

        public int NumberInGroup { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public AchievementType AchievementType { get; set; } = AchievementType.Custom;

        public int? AchievementValue { get; set; }

        public int? ParameterId { get; set; }

        public int? SemesterId { get; set; }

        public EditAchievementViewModel()
        {
        }

        public EditAchievementViewModel(Achievement achievement)
        {
            Id = achievement.Id;
            AchievementsGroupId = achievement.AchievementsGroupId;
            NumberInGroup = achievement.NumberInGroup;
            Name = achievement.Name;
            Description = achievement.Description;
            AchievementType = achievement.AchievementType;
            AchievementValue = achievement.AchievementValue;
            ParameterId = achievement.ParameterId;
            SemesterId = achievement.SemesterId;
        }

        public bool UpdateAchievement(Achievement achievement)
        {
            var result = false;

            if (achievement.Id == Id)
            {
                achievement.AchievementsGroupId = AchievementsGroupId;
                achievement.NumberInGroup = NumberInGroup;
                achievement.Name = Name;
                achievement.Description = Description;
                achievement.AchievementType = AchievementType;
                achievement.AchievementValue = AchievementValue;
                achievement.SemesterId = SemesterId;
                achievement.ParameterId = ParameterId;
                result = true;
            }
            return result;
        }
    }
}

KNI_D6_web/Components/AchievementsProgressViewComponent.cs
using KNI_D6_web.Model;
using KNI_D6_web.Model.Database.Repositories;
using KNI_D6_web.ViewModels.Components.AchievementsProgress;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KNI_D6_web.Components
{
    public class AchievementsProgressViewComponent : ViewComponent
    {
        private readonly ISemestersRepository semestersRepository;
        private readonly IAchievementsGroupsRepository achievementsGroupsRepository;
        private readonly UserManager<User> userManager;

        public AchievementsProgressViewComponent(ISemestersRepository semestersRepository, IAchievementsGroupsRepository achievementsGroupsRepository, UserManager<User> userManager)
        {
            this.semestersRepository = semestersRepository;
            this.achievementsGroupsRepository = achievementsGroupsRepository;
            this.userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync(string login)
        {
            var viewModel = new AchievementsProgressViewModel()
            {
                AchievementsProgressInGroups = await GetAchievementsProgressInGroups(login)
            };
            return View(viewModel);
        }

        private async Task<IEnumerable<IOrderedEnumerable<AchievementProgressViewModel>>> GetAchievementsProgressInGroups(string login)
        {
            var user = await userManager.Users
                .Include(u => u.ParameterValues)
                .Include(u => u.UserAchievements)
                .FirstOrDefaultAsync(u => u.UserName == login);

            var groups = await achievementsGroupsRepository.GetAchievementsGroupsAsync();

            var semester = await semestersRepository.FindCurrentSemesterAsync();

            var progressGroups = new List<IOrderedEnumerable<AchievementProgressViewModel>>();

            foreach (var group in groups.Where(g => g.Ahievements.Any()))
            {
                var progressGroup = new List<AchievementProgressViewModel>();

                var filteredAchievements = semester == null ? 
                    group.Ahievements : 
                    group.Ahievements.Where(
                        a => a.SemesterId == null || 
                        a.SemesterId == semester.Id ||
                        user.UserAchievements.Any(ua => ua.AchievementId == a.Id)
                        );

                foreach (var achievement in filteredAchievements)
                {
                    var linkedParameterValue = user.ParameterValues.Where(pv => pv.ParameterId == achievement.ParameterId).FirstOrDefault();

                    var progress = new AchievementProgressViewModel()
                    {
                        AchievementId = achievement.Id,
                        AchievementName = achievement.Name,
                        AchievementDescription = achievement.Description,
                        NumberInGroup = achievement.NumberInGroup,
                        AchievementValue = achievement.AchievementValue,
                        LinkedParameterValue = linkedParameterValue?.Value,
                        IsReceived = user.UserAchievements.Any(ua => ua.AchievementId == achievement.Id),
                        AchievementType = achievement.AchievementType
                    };
                    progressGroup.Add(progress);
                }
                progressGroups.Add(progressGroup.OrderBy(ap => ap.NumberInGroup));
            }

            return progressGroups.Where(g => g.Any());
        }
    }
}

KNI_D6_web/Controllers/AchievementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KNI_D6_web.Model;
using KNI_D6_web.Model.Achievements;
using KNI_D6_web.Model.Database.Repositories;
using KNI_D6_web.ViewModels.Achievements;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace KNI_D6_web.Controllers
{
    [Authorize]
    [Route("[controller]")]
    public class AchievementsController : Controller
    {
        private readonly IAchievementsManager achievementsManager;
        private readonly ISemestersRepository semestersRepository;
        private readonly IParametersRepository parametersRepository;
        private readonly IAchievementsRepository achievementsRepository;
        private readonly IAchievementsGroupsRepository achievementsGroupsRepository;
        private readonly UserManager<User> userManager;

        public AchievementsController(IAchievementsManager achievementsManager, ISemestersRepository semestersRepository, IParametersRepository parametersRepository, IAchievementsRepository achievementsRepository, IAchievementsGroupsRepository achievementsGroupsRepository, UserManager<User> userManager)
        {
            this.achievementsManager = achievementsManager;
            this.semestersRepository = semestersRepository;
            this.parametersRepository = parametersRepository;
            this.achievementsRepository = achievementsRepository;
            this.achievementsGroupsRepository = achievementsGroupsRepository;
            this.userManager = userManager;
        }

        [AllowAnonymous]
        [HttpGet, ActionName("Index")]
        public async Task<IActionResult> Index()
        {
            var viewModel = new AchievementsViewModel()
            {
                AchievementsInGroups = await GetAchievementsInGroups()
            };
            return View(viewModel);                
        }

        [AllowAnonymous]
        [HttpGet, Route("Progress")]
        public IActionResult Progress(string userLogin)
        {
            return View(new AchievementsProgressViewModel() { Login = userLogin });
        }

        [HttpGet, Route("All")]
        public async Task<IActionResult> All()
        {
            var viewModel = new AchievementsViewModel()
            {
                AchievementsInGroups = await GetAllAchievementsInGroups()
            };
            return View(viewModel);
        }

        [Authorize(Roles = UserRoles.Admin)]
        [HttpGet, Route("Create")]
        public async Task<IActionResult> Create()
        {
            ViewData["Parameters"] = await CreateParametersList(null);
            ViewData["AchievementGroups"] = await CreateAchievementGroupsList(null);
            ViewData["SemestersSelectList"] = await CreateSemestersSelectList(null);

            return View(new CreateAchievementViewModel());
        }

        [Authorize(Roles = UserRoles.Admin)]
        [HttpPost, Route("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("AchievementName, AhievementDescription, AchievementValue, ParameterId, NumberInGroup, GroupId, SemesterId, AchievementType")] CreateAchievementViewModel viewModel)
        {

            if (!ModelState.IsValid)
            {
                ViewData["Parameters"] = await CreateParametersList(viewModel.ParameterId);
                ViewData["AchievementGroups"] = await CreateAchievementGroupsList(viewModel.GroupId);
                ViewData["SemestersSelectList"] = await CreateSemestersSelectList(viewModel.SemesterId);
                return View(viewModel);
            }

            var achievement = new Achievement()
            {
                Name = viewModel.AchievementName,
                Description = viewModel.AhievementDescription,
                AchievementValue = viewModel.AchievementValue,
                ParameterId = viewModel.ParameterId,
                AchievementsGroupId = viewModel.GroupId,
                NumberInGroup = viewModel.NumberInGroup,
                SemesterId = viewModel.SemesterId,
                AchievementType = viewModel.AchievementType
            };

            IActionResult result;
            try
            {
                int id = await achievementsRepository.AddAchievementAsync(achievement);
                await achievementsManager.CheckAndUpdateСalculatedAchievementForUsers(userManager.Users.Select(u => u.Id), id);
                result = RedirectToAction(nameof(All));
            }
            catch (Exception ex)
            {
                result = StatusCode(StatusCodes.Status500InternalServerError, ex);
            }            
            return result;
        }

        [AllowAnonymous]
        [HttpGet, Route("Details")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return BadRequest();
            
            var achievement = await achievementsRepository.FindAchievementByIdAsync(id.Value);
            if (achievement == null)
                return NotFound($"Achievement with id {id} not found");

            return View(achievement);
        }

        [Authorize(Roles = UserRoles.Admin)]
        [HttpGet, Route("Edit")]
        public async Task<IActionResult> Edit(int id)
        {
            if (!ModelState.IsValid)
                return BadRequest();
       
            var achievement = await achievementsRepository.FindAchievementByIdAsync(id);
            if (achievement == null)
                return NotFound($"Achievement with id {id} not found");

            
            var viewModel = new EditAchievementViewModel(achievement);
            ViewData["AchievementsGroupId"] = await CreateAchievementGroupsList(achievement.AchievementsGroupId);
            ViewData["Parameters"] = await CreateParametersList(achievement.ParameterId);
            ViewData["SemestersSelectList"] = await CreateSemestersSelectList(achievement.SemesterId);
            return View(viewModel);            
        }

        [Authorize(Roles = UserRoles.Admin)]
        [HttpPost, Route("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, 
            [Bind("Id,AchievementsGroupId,NumberInGroup,Name,Description,AchievementType,AchievementValue,ParameterId,SemesterId")] EditAchievementViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                ViewData["AchievementsGroupId"] = await CreateAchievementGroupsList(viewModel.AchievementsGroupId);
                ViewData["Parameters"] = await CreateParametersList(viewModel.ParameterId);
                ViewData["SemestersSelectList"] = await CreateSemestersSelectList(viewModel.SemesterId);
                return View(viewModel);
            }

            if (id != viewModel.Id)
                return BadRequest();

            var achievement = await achievementsRepository.FindAchievementByIdAsync(id);
            if (achievement == null)
                return NotFound($"Achievement with Id {id} not found");

            IActionResult result;
            try
            {        
                viewModel.UpdateAchievement(achievement);

                await achievementsRepository.UpdateAchievementAsync(achievement);
                
                await achievementsManager.CheckAndUpdateСalculatedAchievementForUsers(userManager.Users.Select(u => u.Id), id);
                result = RedirectToAction(nameof(All));
            }
            catch (Exception ex)
            {
                result = StatusCode(StatusCodes.Status500InternalServerError, ex);
            }
            return result;
        }

        [Authorize(Roles = UserRoles.Admin)]
        [HttpGet, Route("Delete")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return BadRequest();

            var achievement = await achievementsRepository.FindAchievementByIdAsync(id.Value);
            if (achievement == null)
                return NotFound($"Achievement with Id {id} not found");

            return View(achievement);
        }

        [Authorize(Roles = UserRoles.Admin)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await achievementsRepository.RemoveAchievementByIdAsync(id);
                return RedirectToAction(nameof(All));
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex);
            }
        }

        private async Task<SelectList> CreateParametersList(int? currentId)
        {
            var tmpList = (await parametersRepository.GetParametersAsync())
                .Select(p => new CustomSelectListItem() { Name = p.Name, Id = p.Id }).ToList();
            tmpList.Insert(0, new CustomSelectListItem() { Name = "Без параметра", Id = null });
            return new SelectList(tmpList, "Id", "Name", currentId);
        }
        
        private async Task<SelectList> CreateAchievementGroupsList(int? currentId)
        {
            return new SelectList(await achievementsGroupsRepository.GetAchievementsGroupsAsync(), "Id", "Name", currentId);
        }

        private async Task<SelectList> CreateSemestersSelectList(int? currentId)
        {
            var tmpList = (await semestersRepository.GetSemestersAsync())
                .Select(s => new CustomSelectListItem() { Name = s.Name, Id = s.Id }).ToList();
            tmpList.Insert(0, new CustomSelectListItem() { Name = "Без семестра", Id = null });
            return new SelectList(tmpList, "Id", "Name", currentId);
        }

KNI_D6_web/Views/Achievements/All.cshtml
@model KNI_D6_web.ViewModels.Achievements.AchievementsViewModel
@using KNI_D6_web.Model;
@{
    ViewData["Title"] = "Достижения";
}


<h1>Все достижения</h1>

@if (User.IsInRole(UserRoles.Admin))
{
<div class="text-center">
    <h4>Администрирование</h4>
    <!--
    <div class="dropdown">
        <a class="btn btn-outline-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Добавить достижение
        </a>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" asp-controller="Achievements" asp-action="CreateValueAchievement">Вычисляемое</a>
            <a class="dropdown-item" asp-controller="Achievements" asp-action="CreateCustomAchievement">Невычисляемое</a>
        </div>
    </div> -->
    <a class="btn btn-outline-primary m-2" asp-controller="Achievements" asp-action="Create">Добавить достижение</a>
    <a class="btn btn-outline-info m-2" asp-controller="AchievementGroups" asp-action="Index">Группы достижений</a>
</div>
}

<div>
    <div class="py-3">
        @foreach (var group in Model.AchievementsInGroups)
        {
            <div class="container rounded rounded-lg m-2 ">
                <ul class="list-unstyled">
                    @foreach (var item in group)
                    {
                        <li class="media border bg-light border-secondary rounded rounded-lg p-2 m-1">
                            <!--<img src="..." class="mr-3" alt="...">-->
                            <div class="media-body">
                                <h5 class="mt-0 mb-1">@item.Name</h5>
                                @item.Description
                                <br />
                                Тип: @item.AchievementType.ToString()
                                @if(item.Parameter != null)
                                {
                                    <br />
                                    <p>Параметр: @item.Parameter?.Name, значение: @item.AchievementValue</p>
                                }
                                <hr/>
                                @if (User.IsInRole(UserRoles.Admin))
                                {
                                    <div>
                                        <a class="btn btn-sm btn-warning ml-1" asp-action="Edit" asp-route-id="@item.Id"> Изменить </a>
                                        <a class="btn btn-sm btn-primary ml-1" asp-action="Details" asp-route-id="@item.Id"> Подробнее </a>
                                        <a class="btn btn-sm btn-danger ml-1" asp-action="Delete" asp-route-id="@item.Id"> Удалить </a>
                                    </div>
                                }
                            </div>
                        </li>

                    }
                </ul>
            </div>
            <br>
        }
    </div>
</div>

KNI_D6_web/Views/Achievements/Create.cshtml
@model KNI_D6_web.ViewModels.Achievements.CreateAchievementViewModel
@using KNI_D6_web.Model.Achievements;

@{
    ViewData["Title"] = "Добавление вычисляемого достижения";
}

<h1>Добавление вычисляемого достижения</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateValueAchievement">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AchievementName" class="control-label">Название</label>
                <input asp-for="AchievementName" class="form-control" />
                <span asp-validation-for="AchievementName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AhievementDescription" class="control-label">Описание</label>
                <input asp-for="AhievementDescription" class="form-control" />
                <span asp-validation-for="AhievementDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AchievementType" class="control-label">Тип достижения</label>
                <select asp-for="AchievementType" asp-items="Html.GetEnumSelectList<AchievementType>()" class="form-control"></select>
                <span asp-validation-for="AchievementType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParameterId" class="control-label">Параметр</label>
                <select asp-for="ParameterId" class="form-control" asp-items="ViewBag.Parameters"></select>
                <span asp-validation-for="ParameterId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AchievementValue" class="control-label">Значение параметра для получения достижения</label>
                <input asp-for="AchievementValue" class="form-control" />
                <span asp-validation-for="AchievementValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label">Группа</label>
                <select asp-for="GroupId" class="form-control" asp-items="ViewBag.AchievementGroups"></select>
                <span asp-validation-for="GroupId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberInGroup" class="control-label">Номер в группе</label>
                <input asp-for="NumberInGroup" class="form-control" />
                <span asp-validation-for="NumberInGroup" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SemesterId" class="control-label">Семестр</label>
                <select asp-for="SemesterId" class="form-control" asp-items="ViewBag.SemestersSelectList"></select>
                <span asp-validation-for="SemesterId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-primary" asp-action="All">К списку достижений</a>
</div>

KNI_D6_web/Views/Achievements/CreateValueAchievement.cshtml
@model KNI_D6_web.ViewModels.Achievements.CreateValueAchievementViewModel

@{
    ViewData["Title"] = "Добавление вычисляемого достижения";
}

<h1>Добавление вычисляемого достижения</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateValueAchievement">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AchievementName" class="control-label">Название</label>
                <input asp-for="AchievementName" class="form-control" />
                <span asp-validation-for="AchievementName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AhievementDescription" class="control-label">Описание</label>
                <input asp-for="AhievementDescription" class="form-control" />
                <span asp-validation-for="AhievementDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AchievementValue" class="control-label">Значение параметра для получения достижения</label>
                <input asp-for="AchievementValue" class="form-control" />
                <span asp-validation-for="AchievementValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParameterId" class="control-label">Параметр</label>
                <select asp-for="ParameterId" class="form-control" asp-items="ViewBag.Parameters"></select>
                <span asp-validation-for="ParameterId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label">Группа</label>
                <select asp-for="GroupId" class="form-control" asp-items="ViewBag.AchievementGroups"></select>
                <span asp-validation-for="GroupId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberInGroup" class="control-label">Номер в группе</label>
                <input asp-for="NumberInGroup" class="form-control" />
                <span asp-validation-for="NumberInGroup" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SemesterId" class="control-label">Семестр</label>
                <select asp-for="SemesterId" class="form-control" asp-items="ViewBag.SemestersSelectList"></select>
                <span asp-validation-for="SemesterId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-primary" asp-action="All">К списку достижений</a>
</div>

KNI_D6_web/Views/Achievements/Delete.cshtml
@model KNI_D6_web.Model.Achievements.Achievement
@using KNI_D6_web.Model;
@{
    ViewData["Title"] = "Удаление достижения";
}

<h1>Удаление достижения</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Группа достижений
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AchievementGroup.Name)
        </dd>
        <dt class="col-sm-2">
            Номер в группе
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberInGroup)
        </dd>
        <dt class="col-sm-2">
            Название
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Описание
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            Тип достижения
        </dt>
        <dd class="col-sm-10">
            @Model.AchievementType.GetDescription()
        </dd>
        <dt class="col-sm-2">
            Связанный параметр
        </dt>
        <dd class="col-sm-10">
            @(Model.Parameter != null ? Model.Parameter.Name : "Нет связанного параметра")
        </dd>
        <dt class="col-sm-2">
            Значение параметра для получения достижения
        </dt>
        <dd class="col-sm-10">
            @(Model.AchievementValue.HasValue ? Model.AchievementValue.Value.ToString() : "Нет значения")
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" />
    </form>
</div>

<div class="mt-2">
    <a class="btn btn-outline-primary" asp-action="All">К списку достижений</a>
</div>

KNI_D6_web/Views/Achievements/Details.cshtml
@model KNI_D6_web.Model.Achievements.Achievement
@using KNI_D6_web.Model;
@{
    ViewData["Title"] = "Подробнее о достижении";
}

<h1>Подробнее о достижении</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Группа достижений
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AchievementGroup.Name)
        </dd>
        <dt class="col-sm-2">
            Номер в группе
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberInGroup)
        </dd>
        <dt class="col-sm-2">
            Название
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Описание
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            Тип достижения
        </dt>
        <dd class="col-sm-10">
            @Model.AchievementType.GetDescription()
        </dd>
        <dt class="col-sm-2">
            Связанный параметр
        </dt>
        <dd class="col-sm-10">
            @(Model.Parameter != null ? Model.Parameter.Name : "Нет связанного параметра")
        </dd>
        <dt class="col-sm-2">
            Значение параметра для получения достижения
        </dt>
        <dd class="col-sm-10">
            @(Model.AchievementValue.HasValue ? Model.AchievementValue.Value.ToString() : "Нет значения")
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Id">Изменить</a>
    <a class="btn btn-outline-primary" asp-action="All">К списку достижений</a>
</div>

KNI_D6_web/Views/Achievements/Index.cshtml
@model KNI_D6_web.ViewModels.Achievements.AchievementsViewModel
@using KNI_D6_web.Model;
@{
    ViewData["Title"] = "Достижения";
}


<h1>Достижения</h1>

<div>
    <div class="py-2">
        @foreach (var group in Model.AchievementsInGroups)
        {
            <div class="container rounded rounded-lg m-2 p-2">
                <ul class="list-unstyled">
                    @foreach (var item in group)
                    {
                        <li class="media border bg-light border-secondary rounded rounded-lg p-2 m-1">
                            <!--<img src="..." class="mr-3" alt="...">-->
                            <div class="media-body">
                                <h5 class="mt-0 mb-1">@item.Name</h5>
                                @item.Description
                                <br />
                            </div>
                        </li>
                    }
                </ul>
            </div>
        }
    </div>
</div>

KNI_D6_web/Views/Achievements/Progress.cshtml
@model KNI_D6_web.ViewModels.Achievements.AchievementsProgressViewModel
@{
    ViewData["Title"] = "Прогресс достижений";
}

<h1>Прогресс достижений пользователя @Model.Login</h1>
<div>
    @await Component.InvokeAsync("AchievementsProgress", new { login = Model.Login })
</div>