KNI_D6_web/Controllers/EventsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using KNI_D6_web.Model;
using Microsoft.AspNetCore.Authorization;
using KNI_D6_web.ViewModels.Events;
using Microsoft.AspNetCore.Mvc.Rendering;
using KNI_D6_web.Model.Database.Repositories;
using System;
using Microsoft.AspNetCore.Http;

namespace KNI_D6_web.Controllers
{
    [Authorize(Roles = UserRoles.AdminAndModerator)]
    public class EventsController : Controller
    {
        private readonly ISemestersRepository semestersRepository;
        private readonly IEventsRepository eventsRepository;
        private readonly IUserEventsRepository userEventsRepository;
        private readonly IUsersRepository usersRepository;

        public EventsController(ISemestersRepository semestersRepository, IEventsRepository eventsRepository, IUserEventsRepository userEventsRepository, IUsersRepository usersRepository)
        {
            this.semestersRepository = semestersRepository;
            this.eventsRepository = eventsRepository;
            this.userEventsRepository = userEventsRepository;
            this.usersRepository = usersRepository;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var semester = await semestersRepository.FindCurrentSemesterAsync();
            var events = semester != null ?
                (await eventsRepository.GetEventsAsync(semester.Id)).OrderBy(x => x.Date) :
                (await eventsRepository.GetEventsAsync()).OrderBy(x => x.Date);

            var futureEvents = events.Where(e => e.Date > DateTime.Now.Date);

            var pastEvents = events.Except(futureEvents);

            var viewModel = new EventsViewModel()
            {
                PastEvents = pastEvents,
                FutureEvents = futureEvents
            };

            return View(viewModel);
        }


        [HttpGet, Route("[controller]/All")]
        public async Task<IActionResult> All()
        {
            var events = (await eventsRepository.GetEventsAsync()).OrderByDescending(x => x.Date);
            var futureEvents = events.Where(e => e.Date > DateTime.Now.Date);
            var pastEvents = events.Except(futureEvents);

            var viewModel = new EventsViewModel()
            {
                PastEvents = pastEvents,
                FutureEvents = futureEvents
            };

            return View("Index", viewModel);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();
            var entity = await eventsRepository.FindEventByIdAsync(id.Value);

            if (entity == null)
                return NotFound();

            return View(entity);
        }

        public async Task<IActionResult> Create()
        {
            ViewData["SemestersSelectList"] = await CreateSemestersSelectList(null);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Date,SemesterId,IsSpecial")] Event @event)
        {
            if (!ModelState.IsValid)
            {
                ViewData["SemestersSelectList"] = await CreateSemestersSelectList(@event.SemesterId);
                return View(@event);
            }

            IActionResult result;
            try
            {
                await eventsRepository.AddEventAsync(@event);
                result = RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                result = StatusCode(StatusCodes.Status500InternalServerError, ex);
            }
            return result;

        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var entity = await eventsRepository.FindEventByIdAsync(id.Value);
            if (entity == null)
                return NotFound();

            ViewData["SemestersSelectList"] = await CreateSemestersSelectList(null);
            return View(entity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Date,SemesterId,IsSpecial")] Event @event)
        {
            if (!ModelState.IsValid)
            {
                ViewData["SemestersSelectList"] = await CreateSemestersSelectList(@event.SemesterId);
                return View(@event);
            }

            if (id != @event.Id)
                return BadRequest();

            IActionResult result;
            try
            {
                await eventsRepository.UpdateEventAsync(@event);
                result = RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                result = StatusCode(StatusCodes.Status500InternalServerError, ex);
            }
            return result;
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var entity = await eventsRepository.FindEventByIdAsync(id.Value);
            if (entity == null)
                return NotFound();

            return View(entity);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            IActionResult result;
            try
            {
                await eventsRepository.RemoveEventByIdAsync(id);
                result = RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                result = StatusCode(StatusCodes.Status500InternalServerError, ex);
            }
            return result;
        }

        [HttpGet, Route("[controller]/EventVisitors/{id}")]
        public async Task<IActionResult> EventVisitors(int id)
        {
            var entity = await eventsRepository.FindEventByIdAsync(id);
            if (entity == null)
                return NotFound();

            var visitors = (await usersRepository.GetUsersWithLinksAsync()).Select(u => new EventVisitorViewModel()
            {
                Login = u.UserName,
                UserId = u.Id,
                IsVisited = u.UserEvents.Any(ue => ue.EventId == id)
            }).ToList();
            visitors.Sort((x, y) => string.Compare(x.Login, y.Login));

            var viewModel = new EventVisitorsViewModel()
            {
                EventId = id,
                EventVisitors = visitors
            };
            return View(viewModel);
        }
        
        [Route("[controller]/RemoveUserEvent")]
        public async Task<IActionResult> RemoveUserEvent(string userId, int eventId)
        {
            if (string.IsNullOrWhiteSpace(userId))
                return BadRequest();

            IActionResult result;
            try
            {
                await userEventsRepository.RemoveUserEventAsync(userId, eventId);
                result = RedirectToAction(nameof(EventVisitors), new { id = eventId });
            }
            catch (Exception ex)
            {
                result = StatusCode(StatusCodes.Status500InternalServerError, ex);
            }
            return result;
        }

        [Route("[controller]/AddUserEvent")]
        public async Task<IActionResult> AddUserEvent(string userId, int eventId)
        {
            if (string.IsNullOrWhiteSpace(userId))
                return BadRequest();

            var userEvent = await userEventsRepository.FindUserEventAsync(userId, eventId);
            if (userEvent != null)
                return BadRequest();

            IActionResult result;
            try
            {
                await userEventsRepository.AddUserEventAsync(new UserEvent() { UserId = userId, EventId = eventId });
                result = RedirectToAction(nameof(EventVisitors), new { id = eventId });
            }
            catch (Exception ex)
            {
                result = StatusCode(StatusCodes.Status500InternalServerError, ex);
            }
            return result;
        }

        private async Task<SelectList> CreateSemestersSelectList(int? currentId)
        {
            var tmpList = (await semestersRepository.GetSemestersAsync()).Select(s => new CustomSelectListItem() { Name = s.Name, Id = s.Id }).ToList();
            tmpList.Insert(0, new CustomSelectListItem() { Name = "Без семестра", Id = null });
            return new SelectList(tmpList, "Id", "Name", currentId);
        }
    }
}

KNI_D6_web/Controllers/SemestersController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using KNI_D6_web.Model;
using KNI_D6_web.Model.Database.Repositories;
using Microsoft.AspNetCore.Authorization;

namespace KNI_D6_web.Controllers
{
    [Authorize(Roles = UserRoles.AdminAndModerator)]
    public class SemestersController : Controller
    {
        private readonly ISemestersRepository semestersRepository;

        public SemestersController(ISemestersRepository semestersRepository)
        {
            this.semestersRepository = semestersRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await semestersRepository.GetSemestersAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Semester semester)
        {
            if (ModelState.IsValid)
            {
                await semestersRepository.AddSemesterAsync(semester);
                return RedirectToAction(nameof(Index));
            }
            return View(semester);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var semester = await semestersRepository.FindSemesterByIdAsync(id.Value);
            if (semester == null)
            {
                return NotFound();
            }
            return View(semester);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,IsCurrent")] Semester semester)
        {
            if (id != semester.Id)
                return NotFound();
            if (!ModelState.IsValid)
                return View(semester);

            if (await semestersRepository.UpdateSemesterAsync(semester))
                return RedirectToAction(nameof(Index));
            else
                return BadRequest();            
        }

        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return BadRequest();

            var semester = await semestersRepository.FindSemesterByIdAsync(id.Value);

            if (semester == null)
                return NotFound();
            else
                return View(semester);
        }

        [Authorize(Roles = UserRoles.Admin)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await semestersRepository.RemoveSemesterByIdAsync(id))
                return RedirectToAction(nameof(Index));
            else
                return BadRequest();
        }

        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> SetAsCurrent(int id)
        {
            if (await semestersRepository.SetSemesterAsCurrentByIdAsync(id))
                return RedirectToAction(nameof(Index));
            else
                return BadRequest();
        }
    }
}

KNI_D6_web/Views/Shared/_Layout.cshtml
@using KNI_D6_web.Model

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KNI_D6_web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/styles.css" />
    <link rel="shortcut icon" href="~/img/logo/cubes.ico" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo/cubes.png" width="30" height="30" class="d-inline-block align-top" alt="">
                    КНИ "Шестигранник"
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Игроки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Admins">Aдмины</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown text-dark">
                                <a class="nav-link dropdown-toggle text-dark" id="navbarDropdownAchievements" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Достижения
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownAchievements">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Achievements" asp-action="Index">Достижения</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Achievements" asp-action="Progress" asp-route-userLogin="@User.Identity.Name">Прогресс</a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Achievements" asp-action="Index">Достижения</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Мероприятия</a>
                        </li>
                        @if (User.IsInRole(UserRoles.Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Админ-панель
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Achievements" asp-action="All">Все достижения</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Semesters" asp-action="Index">Семестры</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Parameters" asp-action="Index">Параметры</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="All">Все мероприятия</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item ">
                            <a class="btn btn-success m-1" asp-controller="Users" asp-action="UserDetailsByLogin" asp-route-login="@User.Identity.Name">@User.Identity.Name</a>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <form method="post" asp-area="" asp-controller="Account" asp-action="Logout">
                                <button class="btn btn-outline-danger m-1" type="submit">Logout</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <form method="get" asp-area="" asp-controller="Account" asp-action="Login">
                                <button class="btn btn-outline-success m-1" type="submit">Login</button>
                            </form>
                        </li>
                        <li class="nav-item">
                            <form method="get" asp-area="" asp-controller="Account" asp-action="Register">
                                <button class="btn btn-outline-primary m-1" type="submit">Register</button>
                            </form>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - KNI_D6_web
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>